name-map:
  â›” å¹¿å‘Šæ‹¦æˆª: adblock
  ğŸš€ é€‰æ‹©ä»£ç†: proxy
  ğŸŒ çªç ´é”åŒº: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - OVERALL
  JP:
    - JP
    - Japan
    - æ—¥
    - ğŸ‡¯ğŸ‡µ
  US:
    - US
    - United States
    - ç¾
    - ğŸ‡ºğŸ‡¸
  CN:
    - CN
    - China
    - ä¸­å›½
    - ğŸ‡¨ğŸ‡³
  HK:
    - HK
    - Hong Kong
    - æ¸¯
    - ğŸ‡­ğŸ‡°
  TW:
    - TW
    - Taiwan
    - å°
    - ğŸ‡¹ğŸ‡¼
  CA:
    - CA
    - Canada
    - åŠ æ‹¿å¤§
    - ğŸ‡¨ğŸ‡¦
  FR:
    - FR
    - French
    - æ³•
    - ğŸ‡«ğŸ‡·
  SG:
    - SG
    - Singapore
    - æ–°åŠ å¡
    - ç‹®åŸ
    - ğŸ‡¸ğŸ‡¬